// Generated by the protocol buffer compiler.  DO NOT EDIT!

package corner.protobuf;

public final class AreaQueryProtocol {
  private AreaQueryProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class AreaQueryBuffer extends
      com.google.protobuf.GeneratedMessage {
    // Use AreaQueryBuffer.newBuilder() to construct.
    private AreaQueryBuffer() {}
    
    private static final AreaQueryBuffer defaultInstance = new AreaQueryBuffer();
    public static AreaQueryBuffer getDefaultInstance() {
      return defaultInstance;
    }
    
    public AreaQueryBuffer getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return corner.protobuf.AreaQueryProtocol.internal_static_corner_model_AreaQueryBuffer_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return corner.protobuf.AreaQueryProtocol.internal_static_corner_model_AreaQueryBuffer_fieldAccessorTable;
    }
    
    // optional string qname = 1;
    private boolean hasQname;
    private java.lang.String qname_ = "";
    public boolean hasQname() { return hasQname; }
    public java.lang.String getQname() { return qname_; }
    
    // optional string qcode = 2;
    private boolean hasQcode;
    private java.lang.String qcode_ = "";
    public boolean hasQcode() { return hasQcode; }
    public java.lang.String getQcode() { return qcode_; }
    
    public static corner.protobuf.AreaQueryProtocol.AreaQueryBuffer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static corner.protobuf.AreaQueryProtocol.AreaQueryBuffer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static corner.protobuf.AreaQueryProtocol.AreaQueryBuffer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static corner.protobuf.AreaQueryProtocol.AreaQueryBuffer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static corner.protobuf.AreaQueryProtocol.AreaQueryBuffer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static corner.protobuf.AreaQueryProtocol.AreaQueryBuffer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static corner.protobuf.AreaQueryProtocol.AreaQueryBuffer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static corner.protobuf.AreaQueryProtocol.AreaQueryBuffer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(corner.protobuf.AreaQueryProtocol.AreaQueryBuffer prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using corner.protobuf.AreaQueryProtocol.AreaQueryBuffer.newBuilder()
      private Builder() {}
      
      corner.protobuf.AreaQueryProtocol.AreaQueryBuffer result = new corner.protobuf.AreaQueryProtocol.AreaQueryBuffer();
      
      @Override
      protected corner.protobuf.AreaQueryProtocol.AreaQueryBuffer internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new corner.protobuf.AreaQueryProtocol.AreaQueryBuffer();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return corner.protobuf.AreaQueryProtocol.AreaQueryBuffer.getDescriptor();
      }
      
      public corner.protobuf.AreaQueryProtocol.AreaQueryBuffer getDefaultInstanceForType() {
        return corner.protobuf.AreaQueryProtocol.AreaQueryBuffer.getDefaultInstance();
      }
      
      public corner.protobuf.AreaQueryProtocol.AreaQueryBuffer build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private corner.protobuf.AreaQueryProtocol.AreaQueryBuffer buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public corner.protobuf.AreaQueryProtocol.AreaQueryBuffer buildPartial() {
        corner.protobuf.AreaQueryProtocol.AreaQueryBuffer returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional string qname = 1;
      public boolean hasQname() {
        return result.hasQname();
      }
      public java.lang.String getQname() {
        return result.getQname();
      }
      public Builder setQname(java.lang.String value) {
        result.hasQname = true;
        result.qname_ = value;
        return this;
      }
      public Builder clearQname() {
        result.hasQname = false;
        result.qname_ = "";
        return this;
      }
      
      // optional string qcode = 2;
      public boolean hasQcode() {
        return result.hasQcode();
      }
      public java.lang.String getQcode() {
        return result.getQcode();
      }
      public Builder setQcode(java.lang.String value) {
        result.hasQcode = true;
        result.qcode_ = value;
        return this;
      }
      public Builder clearQcode() {
        result.hasQcode = false;
        result.qcode_ = "";
        return this;
      }
    }
    
    static {
      corner.protobuf.AreaQueryProtocol.getDescriptor();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_corner_model_AreaQueryBuffer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_corner_model_AreaQueryBuffer_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String descriptorData =
      "\n\037corner/protobuf/AreaQuery.proto\022\014corne" +
      "r.model\"/\n\017AreaQueryBuffer\022\r\n\005qname\030\001 \001(" +
      "\t\022\r\n\005qcode\030\002 \001(\tB$\n\017corner.protobufB\021Are" +
      "aQueryProtocol";
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_corner_model_AreaQueryBuffer_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_corner_model_AreaQueryBuffer_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_corner_model_AreaQueryBuffer_descriptor,
              new java.lang.String[] { "Qname", "Qcode", },
              corner.protobuf.AreaQueryProtocol.AreaQueryBuffer.class,
              corner.protobuf.AreaQueryProtocol.AreaQueryBuffer.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
}
